### ISSUE TITLE
Lower Chances For Infection

### ISSUE THREAD

**Issue by kanmingxu00** [VishalRamesh50/Husky-Bot#29]
The chances for infection are too high, 1/3 cap is crazy high, that's basically just getting infected every message. Make the cap like 1/20 at the most. Also make the listenermax and sendermax higher, like more than 200, like 2000 or something. Everyones going to be infected at this rate, which isn't very exciting.

**Comment by VishalRamesh50** [comment]
Contrary to what you might think infection rates are going at a reasonable pace. Sender and Listener rates are already at 200 and 2000 respectively. And that 1/3 cap hasn't really been hit in most cases. However just to make things a bit more interesting we've decreased the rate of infection to make it a little harder to get infected.
